#!/usr/bin/env bash
# Syncs the Omarchy Radio playlist (omacom/radio.omarchy.org) into assets/music/radio/.
# Downloads playlist.json, every track it lists, and any .lrc lyrics files. Idempotent:
# tracks already present and larger than 100 KB are skipped. Requires curl and python3.
# Usage: tools/sync-radio.sh [-j N]   (N parallel downloads, default 6)
#
# Opt-out: put a track's file name in EXCLUDE below. Excluded entries are stripped from the
# playlist.json we write, are never downloaded and never listed in docs/CREDITS.md, so an
# artist who objects stays out across re-syncs (delete any already-downloaded file once).
set -euo pipefail
cd "$(dirname "$0")/.."
jobs=6
if [[ "${1:-}" == "-j" ]]; then jobs="${2:-6}"; fi

# Tracks to leave out entirely, by file name as it appears in playlist.json. Example:
# EXCLUDE=("some-artist-some-song.mp3")
EXCLUDE=()

REPO_RAW="https://raw.githubusercontent.com/omacom/radio.omarchy.org/main/public/tracks"
SITE="https://radio.omarchy.org/tracks"
API="https://api.github.com/repos/omacom/radio.omarchy.org/contents/public/tracks/lyrics"
dest="assets/music/radio"
mkdir -p "$dest/lyrics"

echo "fetching playlist.json"
curl -fsSL "$REPO_RAW/playlist.json" -o "$dest/playlist.json.tmp"
# Validate the JSON, drop excluded tracks, then publish the filtered playlist.
python3 - "$dest/playlist.json.tmp" "$dest/playlist.json.filtered" \
  ${EXCLUDE[@]+"${EXCLUDE[@]}"} <<'PYFILTER'
import json, sys

src, out = sys.argv[1], sys.argv[2]
excluded = set(sys.argv[3:])
data = json.load(open(src, encoding="utf-8"))
all_tracks = data.get("tracks", [])
kept = [t for t in all_tracks if t.get("file") not in excluded]
data["tracks"] = kept
json.dump(data, open(out, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
dropped = len(all_tracks) - len(kept)
print("playlist: %d tracks%s" % (len(kept), ", %d excluded" % dropped if dropped else ""))
PYFILTER
rm -f "$dest/playlist.json.tmp"
mv "$dest/playlist.json.filtered" "$dest/playlist.json"

# Downloads one file, trying the site first then the raw GitHub mirror.
fetch_track() {
  local file="$1"
  local out="$dest/$file"
  if [[ -f "$out" ]] && [[ $(stat -c %s "$out") -gt 102400 ]]; then
    echo "skip  $file"
    return 0
  fi
  local tmp="$out.part"
  if curl -fsSL --retry 3 --retry-delay 2 "$SITE/$file" -o "$tmp" \
    || curl -fsSL --retry 3 --retry-delay 2 "$REPO_RAW/$file" -o "$tmp"; then
    if [[ $(stat -c %s "$tmp") -gt 102400 ]]; then
      mv "$tmp" "$out"
      echo "ok    $file ($(du -h "$out" | cut -f1))"
      return 0
    fi
  fi
  rm -f "$tmp"
  echo "FAIL  $file" >&2
  return 1
}
export -f fetch_track
export dest SITE REPO_RAW

# A flaky download must not abort the run: the lyrics fetch and the CREDITS regeneration below
# are exactly what a re-run is meant to heal. Failures are reported in the exit code instead.
failed=0
python3 -c '
import json,sys
for t in json.load(open(sys.argv[1]))["tracks"]:
    print(t["file"])
' "$dest/playlist.json" | xargs -P "$jobs" -I{} bash -c 'fetch_track "$@"' _ {} || failed=1

echo "fetching lyrics"
lyrics=$(curl -fsSL "$API" | python3 -c '
import json,sys
for e in json.load(sys.stdin):
    if e["name"].endswith(".lrc"):
        print(e["name"])
' || true)
for lrc in $lyrics; do
  if curl -fsSL --retry 3 "$REPO_RAW/lyrics/$lrc" -o "$dest/lyrics/$lrc.tmp"; then
    mv "$dest/lyrics/$lrc.tmp" "$dest/lyrics/$lrc"
    echo "ok    lyrics/$lrc"
  else
    rm -f "$dest/lyrics/$lrc.tmp"
    echo "FAIL  lyrics/$lrc" >&2
    failed=1
  fi
done

echo "regenerating docs/CREDITS.md"
python3 - "$dest/playlist.json" docs/CREDITS.md <<'PY'
import json, sys
playlist = json.load(open(sys.argv[1], encoding="utf-8"))
tracks = playlist["tracks"]
lines = [
    "# Credits",
    "",
    "## Music - Omarchy Radio",
    "",
    "Tracks are artist-submitted songs set in the Omarchy universe, bundled from",
    "[radio.omarchy.org](https://radio.omarchy.org) (repository `omacom/radio.omarchy.org`).",
    "Every track and artist is listed below and on the in-game credits screen; the current",
    "track is shown as a toast when it changes. Explicit tracks can be filtered in Settings.",
    "If an artist objects, add their file name to the `EXCLUDE` list at the top of",
    "`tools/sync-radio.sh`; the track is then dropped from the bundled playlist, from the",
    "download set and from this list on the next sync.",
    "",
    "<!-- generated by tools/sync-radio.sh from playlist.json; do not edit by hand -->",
    "",
    "| Title | Artist | Notes |",
    "|-------|--------|-------|",
]
for t in tracks:
    notes = []
    if t.get("explicit"):
        notes.append("explicit")
    if "oligarchy" in t["title"].lower():
        notes.append("boss track")
    if t["title"].lower() == "public code, private yacht":
        notes.append("Oligarch menu")
    title = t["title"].replace("|", "\\|")
    lines.append("| %s | %s | %s |" % (title, t["artist"], ", ".join(notes)))
lines += [
    "",
    "%d tracks. Fallback chiptune loops in `assets/music/fallback/` are generated in-house" % len(tracks),
    "by `tools/gen-music.py`.",
    "",
    "## Sound effects",
    "",
    "All sound effects are procedurally generated in-house by `tools/gen-sfx.py`",
    "(jsfxr-style synthesis, committed as WAV).",
    "",
    "## Fonts",
    "",
    "- Press Start 2P - CodeMan38 - SIL Open Font License 1.1",
    "- Silkscreen - Jason Kottke - SIL Open Font License 1.1",
    "- VT323 - Peter Hull - SIL Open Font License 1.1",
    "",
    "## Art",
    "",
    "Sprites, tiles and effects are procedurally generated in-house (see `docs/GAME_DESIGN.md` 10.1);",
    "environment art is recoloured live from the active Omarchy theme.",
    "",
]
open(sys.argv[2], "w", encoding="utf-8").write("\n".join(lines))
PY

count=$(find "$dest" -maxdepth 1 -name '*.mp3' | wc -l)
echo "done: $count tracks, $(du -sh "$dest" | cut -f1) in $dest"
if [[ "$failed" != "0" ]]; then
  echo "some downloads failed; re-run tools/sync-radio.sh to retry" >&2
  exit 1
fi
